// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMq1mYe3SDbFRn3Ad1ARF9QZcBKiXvzs',
    appId: '1:333663125060:web:5a476882549357eebd4611',
    messagingSenderId: '333663125060',
    projectId: 'myapp-306c7',
    authDomain: 'myapp-306c7.firebaseapp.com',
    storageBucket: 'myapp-306c7.firebasestorage.app',
    measurementId: 'G-4LPCP8DBGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAba609WCYduI2Cv4TtGRZvP7-fFZcroJc',
    appId: '1:333663125060:android:f4769c4a42ec03f4bd4611',
    messagingSenderId: '333663125060',
    projectId: 'myapp-306c7',
    storageBucket: 'myapp-306c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Tv0GU2_Dt2qtHPdrbjkm2FSX0v3rqu0',
    appId: '1:333663125060:ios:1cd965b54e88eedebd4611',
    messagingSenderId: '333663125060',
    projectId: 'myapp-306c7',
    storageBucket: 'myapp-306c7.firebasestorage.app',
    iosBundleId: 'com.localbiz.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1Tv0GU2_Dt2qtHPdrbjkm2FSX0v3rqu0',
    appId: '1:333663125060:ios:1cd965b54e88eedebd4611',
    messagingSenderId: '333663125060',
    projectId: 'myapp-306c7',
    storageBucket: 'myapp-306c7.firebasestorage.app',
    iosBundleId: 'com.localbiz.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMq1mYe3SDbFRn3Ad1ARF9QZcBKiXvzs',
    appId: '1:333663125060:web:290d6b12e661cc69bd4611',
    messagingSenderId: '333663125060',
    projectId: 'myapp-306c7',
    authDomain: 'myapp-306c7.firebaseapp.com',
    storageBucket: 'myapp-306c7.firebasestorage.app',
    measurementId: 'G-M4RG2687ML',
  );

}